### ISSUE TITLE
Other tags then `latest` on docker hub?

### ISSUE THREAD

**Issue by se-jaeger** [EasyPi/docker-scrapyd#1]
Could you add/use docker tags and publish them on docker hub?

This would be very helpful.

Anyways, thanks for offer this Image!

**Comment by vimagick** [comment]
implemented as [easypi/scrapyd:1.3.0-2.6.1][1]

- scrapyd_version: 1.3.0
- scrapy_version: 2.6.1

[1]: https://hub.docker.com/r/easypi/scrapyd/tags
