### ISSUE TITLE
Plans to publish python 3.10 container?

### ISSUE THREAD

**Issue by se-jaeger** [EasyPi/docker-scrapyd#2]
Hi,

do you plan to build and publish a image based on python 3.10?
Both scrapy and scrapyd now support 3.10. Would be very appreciated!

**Comment by vimagick** [comment]
I'm using the base image: debian:11
Python 3.10 will be in the [debian 12][1] (2023-??-??) 😸 

[1]: https://packages.debian.org/search?suite=bookworm&keywords=python3

**Comment by se-jaeger** [comment]
oh yeah sure that explains why could not manage to install python 3.10 🙈 

What do you think about using `python:3.10.6-slim-bullseye` instead? At least it builds without errors.

**Comment by vimagick** [comment]
`easypi/scrapyd:1.4.3-2.11.0` is based on `debian:bookworm` (with `python3.11`)
